config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  devise_scope :user do
    root to: "devise/sessions#new"
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  resources :lunches do
    resources :groups
  end
  # resources :groups

end

app/models/group.rb
class Group < ActiveRecord::Base

  validates_presence_of :user_id, :lunch_id
  validates_uniqueness_of :user_id, scope: :lunch_id

  belongs_to :lunches
  belongs_to :users
  
end

app/models/lunch.rb
class Lunch < ActiveRecord::Base

validates_presence_of :name, :price, :date, :time

  CATEGORIES = %w[¯\\_(ツ)_/¯ italian american seafood sushi chinese thai vietnamese desserts bakery japanese hamburgers cajun pizza other]
  validates :category, inclusion: { in: CATEGORIES, allow_blank: true }

  PRICES = %w[$ $$ $$$ $$$$ $$$$$]
  validates :price, inclusion: { in: PRICES }

  has_many :groups
  has_many :users,
    through: :groups
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :groups
  has_many :lunches,
    through: :groups

  devise :trackable, :omniauthable, omniauth_providers: [:github]

  validates :provider, presence: true, inclusion: ["github"]
  validates :uid, presence: true

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid)
  end

  def update_from_omniauth(auth)
    self.email = auth.info.email
    self.name = auth.info.name
    self.image = auth.info.image
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def new_session_path(_scope)
  root_path
end

def after_sign_in_path_for(user)
  lunches_path
end

def after_sign_out_path_for(_resource)
  root_path
end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      @user.update_from_omniauth(request.env["omniauth.auth"])
      flash[:notice] = "Signed in as #{@user.name}"
      sign_in_and_redirect @user
    else
      binding.pry
      session["devise.github_data"] = request.env["omniauth.auth"]
      flash[:alert] = "Invalid credentials returned from Github"
      redirect_to root_path
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
    @group = Group.new
  end

  def create
    @lunch = Lunch.find(params[:lunch_id].to_i)
    @group = Group.new(lunch_id: @lunch.id, user_id: current_user.id)
    # @lunch.users << current_user
    # current_user.lunches << @lunch

    if @group.save
      flash[:notice] =  'Lunch joined!'
      redirect_to lunches_path
    else
      flash[:notice] =  'PROBLEM.'
      redirect_to lunches_path
    end
  end

  protected
   def group_params
    params.require(:group).permit(:user_id, :lunch_id)
   end

end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController

  def index
     @lunches = Lunch.where("date > current_timestamp - (20 * interval '1 minute')").order(:date, :time)
  end

  def new
    @lunch = Lunch.new
    @categories = Lunch::CATEGORIES
    @prices = Lunch::PRICES
  end

  def create
		@lunch = Lunch.new(lunch_params )
    @lunch.date = params[:date]
    @lunch.time = params[:time]
		if @lunch.save
			flash[:notice] =  'Lunch Successfully Added!'
			redirect_to @lunch
		else
			flash[:notice] =  'Fill that out.'
			render :new
		end
	end

  def show
    @user = current_user
    @lunch = Lunch.find(params[:id].to_i)
  end

  protected
   def lunch_params
    params.require(:lunch).permit(:location, :description, :category, :price, :date, :time, :name)
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user!


  private

  def authorize_user!
    user = User.find(params[:id])
    unless current_user == user || current_user.admin?
      flash[:alert] = "You Are Not Authorized To View The Page"
      redirect_to after_sign_in_path_for(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
   <% if msg.is_a?(String) %>
     <%= content_tag :div, msg, class: "alert-box #{name} radius" %>
   <% end %>
 <% end %>

app/views/layouts/_nav.html.erb
<nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/lunches">Lunch</a></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <%- if current_user -%>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <%- end -%>
        </ul>
      </section>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <%= render "layouts/nav" %>
 <div class="row">
   <div class="box">
                  <%= render "layouts/flash" %>
           <%= yield %>
   </div>
 </div>
  </body>
</html>

app/views/lunches/index.html.erb
<h2>List of Lunches</h2>
<div class="row">
 <% @lunches.each do |lunch| %>
  <div class="small-9 columns small-centered">
    <article class="event">

        <div class="event-date">
        <p class="event-month"><%=lunch.date.strftime("%b")%></p>
        <p class="event-day"><%=lunch.date.strftime("%d")%></p>
        </div>

        <div class="event-desc">
          <h4 class="event-desc-header"> <%=lunch.name%></h4>
          <p class="event-desc-detail"><span class="event-desc-time"></span><%=lunch.category%> - <%=lunch.time.strftime("%l:%M%p")%> </p>
          <%= link_to "Details", lunch_path(lunch), class:"success button" %>
        </div>

      </article>
     <hr>
  </div>
</div>
 <% end %>
 <br>
 <br>
 <br>
 <%= link_to "Add a new Lunch", new_lunch_path, class:"success button"%>

app/views/lunches/new.html.erb
<h1>Add a Lunch </h1>
<%= form_for @lunch do |f| %>
 <%= f.label :name_of_group %>
 <%= f.text_field :name %>
 <br>

  <%= label_tag(:date, "Date:") %>
  <%= date_field_tag(:date) %>
 <br>
  <%= label_tag(:date, "Time to meet at door:") %>
  <%= time_field_tag(:time) %>
 <br>
 <%= f.label :price_range %>
 <%= f.select :price, @prices%>
 <br>
  Optional Fields
 <br><br>
 <%= f.label :location %>
 <%= f.text_field :location %>
 <br>
 <%= f.label :category %>
 <%= f.select :category, @categories%>
 <br>
 <%= f.label :description %>
 <%= f.text_field :description %>

 <%= f.submit "Add Lunch Group" %>
<% end %>

app/views/lunches/show.html.erb
<br>
<div class="search-results">
      <div class="row ">
        <div class="large-2 columns">
          <a href="#"> <span> </span><img src="<%=@user.image%>" alt="book cover" class=" thumbnail"></a>
        </div>
        <div class="large-10 columns">
          <div class="row">
            <div class=" large-9 columns">
              <h5><a href="#">  <%=@lunch.name%>  </a></h5>
              <p><%= @lunch.date.strftime("%A, %m/%d ") %> | <%= @lunch.time.strftime("Meet at the door at %l:%M%p")%></p>
            </div>
            <div class=" large-3 columns">
              <%= link_to 'Join', lunch_groups_path(@lunch), method: :post, class: "button alert" %>
            </div>
            <div class="row">
              <div class=" large-12 columns">
                <ul class="large-block-grid-2">
                  <li>
                    <ul>
                      <li><strong>Category: </strong><%= @lunch.category %></li>
                      <li><strong>Description:</strong> <%= @lunch.description %> </li>
                    </ul>
                  </li>
                  <li>
                    <ul>
                      <li><strong>Price:</strong> <%= @lunch.price %>  </li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

<br>
<br>
<br>

<%= link_to "List of Lunches", lunches_path %>

app/views/users/show.html.erb
<br>
<div class="search-results">
      <div class="row ">
        <div class="large-2 columns">
          <a href="#"> <span> </span><img src="http://placehold.it/150x200&text=book cover" alt="book cover" class=" thumbnail"></a>
        </div>
        <div class="large-10 columns">
          <div class="row">
            <div class=" large-9 columns">
              <h5>  <%=@user.name%> </h5>
              <p> <%= @lunch.date.strftime("%A, %m/%d ") %> | <%= @lunch.time.strftime("Meet at the door at %l:%M%p")%></p>
            </div>
            <div class="row">
              <div class=" large-12 columns">
                <ul class="large-block-grid-2">
                  <li>
                    <ul>
                      <li><strong>Favorite Color: </strong><%= @lunch.category %></li>
                      <li><strong>Cat or Dog Person:</strong> <%= @lunch.description %> </li>
                    </ul>
                  </li>
                  <li>
                    <ul>
                      <li><strong>Price:</strong> <%= @lunch.price %>  </li>
                    </ul>
                  </li>
                </ul>
            </div>
        </div>
      </div>
    </div>
</div>

<%= @user.events.each do |event| %>
<div class="small-12 medium-6 columns">
        <div class="callout-card warning radius">
          <div class="card-label">
            <div class="label-text">
              <%= event.time.strr####### %>
            </div>
          </div>
          <div class="callout-card-content">
            <h3 class="lead"> <%= link_to ************  event.name %> </h3>
            <ul>
              <li> <%= event.price %> </li>
              <li> <%= event.category %> </li>
              <li> <%= event.description %> </li>
            </ul>
          </div>
        </div>
      </div>

    </div>